language: java

jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # Give xvf some time to start

addons:
  sonarcloud:
    organization: "leanframeworks"
    token:
      secure: "u79szgJuywleogIcsC8S2l8Ch0oZiUnOtQ6nVolW3YXGmqErCT7cvLp/1gxjoN/YgnOZiuEyWxxGK+ATNX8VcvQrSFLR26jbHYKWvvP16EHlU3Xlz4xCFrj4gsBNGZSGEdMGVt2+baHwHTXNWev+9/fmHn5ASB3CjivOHlB7THGDe8GiqypYp0hA9LMbDae/WfVlm/HHyXdJgTGpJDc9gkH+p2dYK3A+I1zi5znxIUlKTeDjqiArqFQcfkb9vWqKpQ6QYo40k0ZnrbJOLULSv0IVSw8T3AE5/KIek5uiyD/CBx124YK2tb/yNqvoHWWvhum5vFinKTlCMFoAxQgYs4kkceCfJFOAs6k4UTPtb+3cU+1AhnhncWog8aZauQ5Uzwek3BQKM6Oo1NnGpO2/GjzXx9GYDpHdjnvDFqJft2rZLsopryxmhxO9102dAodPmOv7qusR81Udoj458QxqAz86g2HuZGhRJFL5hbgdMFhcDg6W6DBdNUcDiT86ThdJKXq3Hmmo1ICT6fvujHECOnxgrNR7VT8zwJo+vq/7O3hh/SZyzx0uczPzir1hmejOM8REAzjZNAK9Pst8LfTagxbXVoekcaunPPVC5XHRJCx2/Uj8sNBEnnqVEblT0N1wAMW4Z/iU+0yzlGNB8hCsS6lNSNWqMc6WRwj5aZ/ufyo="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
